#!/bin/bash
#SBATCH --job-name=LIWP_singlelayer
#SBATCH -n 9
#SBATCH -N 1
#SBATCH -t 4320
#SBATCH -p all
#SBATCH --mem=9000
#SBATCH --open-mode=append
#SBATCH --mail-type=END
#SBATCH --mail-user=phi.richter@iup.physik.uni-bremen.de
module unuse /home/eb/modules/all
module unuse /home/eb/modules/LAMOS
module use /home/eb/modules/_legacy/all
module load Python
module load matplotlib
module load netcdf4-python

python3 TCWret batch_singlelayer/inputs_43
