#!/bin/bash
#SBATCH --job-name=master_LIWP_singlelayer
#SBATCH -n 9
#SBATCH -N 1
#SBATCH -t 4320
#SBATCH -p all
#SBATCH --mem=9000
#SBATCH --open-mode=append
#SBATCH --mail-type=END
#SBATCH --mail-user=phi.richter@iup.physik.uni-bremen.de
module unuse /home/eb/modules/all
module unuse /home/eb/modules/LAMOS
module use /home/eb/modules/_legacy/all
module load Python
module load matplotlib
module load netcdf4-python

sbatch batch_testcases/TC_00
#sleep 20
sbatch batch_testcases/TC_01
#sleep 20
sbatch batch_testcases/TC_02
#sleep 20
sbatch batch_testcases/TC_03
#sleep 20
sbatch batch_testcases/TC_04
#sleep 20
sbatch batch_testcases/TC_05
#sleep 20
sbatch batch_testcases/TC_06
#sleep 20
sbatch batch_testcases/TC_07
#sleep 20
sbatch batch_testcases/TC_08
#sleep 20
sbatch batch_testcases/TC_09
#sleep 20
sbatch batch_testcases/TC_10
#sleep 20
sbatch batch_testcases/TC_11
#sleep 20
sbatch batch_testcases/TC_12
#sleep 20
sbatch batch_testcases/TC_13
#sleep 20
sbatch batch_testcases/TC_14
#sleep 20
sbatch batch_testcases/TC_15
#sleep 20
sbatch batch_testcases/TC_16
#sleep 20
sbatch batch_testcases/TC_17
#sleep 20
sbatch batch_testcases/TC_18
#sleep 20
sbatch batch_testcases/TC_19
#sleep 20
sbatch batch_testcases/TC_20
#sleep 20
sbatch batch_testcases/TC_21
#sleep 20
sbatch batch_testcases/TC_22
#sleep 20
sbatch batch_testcases/TC_23
#sleep 20
sbatch batch_testcases/TC_24
#sleep 20
sbatch batch_testcases/TC_25
#sleep 20
sbatch batch_testcases/TC_26
#sleep 20
sbatch batch_testcases/TC_27
#sleep 20
sbatch batch_testcases/TC_28
#sleep 20
sbatch batch_testcases/TC_29
#sleep 20
sbatch batch_testcases/TC_30
#sleep 20
sbatch batch_testcases/TC_31
#sleep 20
sbatch batch_testcases/TC_32
#sleep 20
