#!/bin/bash
#SBATCH --job-name=master_LIWP_singlelayer
#SBATCH -n 9
#SBATCH -N 1
#SBATCH -t 4320
#SBATCH -p all
#SBATCH --mem=9000
#SBATCH --open-mode=append
#SBATCH --mail-type=END
#SBATCH --mail-user=phi.richter@iup.physik.uni-bremen.de
module unuse /home/eb/modules/all
module unuse /home/eb/modules/LAMOS
module use /home/eb/modules/_legacy/all
module load Python
module load matplotlib
module load netcdf4-python
sbatch batch_singlelayer/LIWP_singlelayer_0
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_1
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_2
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_3
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_4
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_5
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_6
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_7
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_8
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_9
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_10
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_11
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_12
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_13
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_14
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_15
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_16
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_17
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_18
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_19
sleep 20
sbatch batch_singlelayer/LIWP_singlelayer_20
sleep 20
